// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monoProjekt.Data;

#nullable disable

namespace monoProjekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240606071923_abrvbnbkhgnfhdgf")]
    partial class abrvbnbkhgnfhdgf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("monoProjekt.Models.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");
                });

            modelBuilder.Entity("monoProjekt.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MakeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("vehicleMakeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("vehicleMakeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("monoProjekt.Models.VehicleModel", b =>
                {
                    b.HasOne("monoProjekt.Models.VehicleMake", "vehicleMake")
                        .WithMany("VehicleModels")
                        .HasForeignKey("vehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehicleMake");
                });

            modelBuilder.Entity("monoProjekt.Models.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
